# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mac_hw_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mac_hw_info.proto\x12\x08\x62\x62hwinfo\"\xea\x03\n\x06HwInfo\x12+\n\x05inner\x18\x01 \x01(\x0b\x32\x1c.bbhwinfo.HwInfo.InnerHwInfo\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x18\n\x10protocol_version\x18\x03 \x01(\x05\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x11\n\ticloud_ua\x18\x05 \x01(\t\x12\x16\n\x0e\x61oskit_version\x18\x06 \x01(\t\x1a\xc9\x02\n\x0bInnerHwInfo\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x16\n\x0eio_mac_address\x18\x02 \x01(\x0c\x12\x1e\n\x16platform_serial_number\x18\x03 \x01(\t\x12\x15\n\rplatform_uuid\x18\x04 \x01(\t\x12\x16\n\x0eroot_disk_uuid\x18\x05 \x01(\t\x12\x10\n\x08\x62oard_id\x18\x06 \x01(\t\x12\x14\n\x0cos_build_num\x18\x07 \x01(\t\x12\"\n\x1aplatform_serial_number_enc\x18\x08 \x01(\x0c\x12\x19\n\x11platform_uuid_enc\x18\t \x01(\x0c\x12\x1a\n\x12root_disk_uuid_enc\x18\n \x01(\x0c\x12\x0b\n\x03rom\x18\x0b \x01(\x0c\x12\x0f\n\x07rom_enc\x18\x0c \x01(\x0c\x12\x0b\n\x03mlb\x18\r \x01(\t\x12\x0f\n\x07mlb_enc\x18\x0e \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mac_hw_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HWINFO._serialized_start=32
  _HWINFO._serialized_end=522
  _HWINFO_INNERHWINFO._serialized_start=193
  _HWINFO_INNERHWINFO._serialized_end=522
# @@protoc_insertion_point(module_scope)
